# Generated by Django 4.0.2 on 2022-02-02 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('benefit', models.CharField(max_length=255)),
                ('validity', models.CharField(max_length=255)),
                ('operator_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recharge.mobileoperator')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=10)),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1)),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recharge.plan')),
                ('operator_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recharge.mobileoperator')),
            ],
        ),
    ]
