# Generated by Django 4.0.2 on 2022-02-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='benefit',
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
